myrecommendations/myrecommendations/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^myrestaurants/', include('myrestaurants.urls', namespace='myrestaurants')),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# from django.conf import settings

# if settings.DEBUG:
    # urlpatterns += url(
    #         r'^media/(?P<path>.\*)\$',
    #         'django.views.static.serve',
    #         {'document_root': settings.MEDIA_ROOT }
    #         ),

myrecommendations/myrestaurants/urls.py
from django.conf.urls import url
from django.utils import timezone
from django.views.generic import DetailView, ListView, UpdateView
from . models import Restaurant, Dish
from . forms import RestaurantForm, DishForm
from . views import RestaurantCreate, DishCreate, RestaurantDetail, review

urlpatterns = [
    # List latest 5 restaurants: /myrestaurants/
    url(r'^$',
        ListView.as_view(
            queryset=Restaurant.objects.filter(date__lte=timezone.now()).order_by('date')[:5],
            context_object_name='latest_restaurant_list',
            template_name='myrestaurants/restaurant_list.html'),
        name='restaurant_list'),

    # Restaurant details, ex.: /myrestaurants/restaurants/1/
    url(r'^restaurants/(?P<pk>\d+)/$',
        RestaurantDetail.as_view(),
        name='restaurant_detail'),

    # Restaurant dish details, ex: /myrestaurants/restaurants/1/dishes/1/
    url(r'^restaurants/(?P<pkr>\d+)/dishes/(?P<pk>\d+)/$',
        DetailView.as_view(
            model=Dish,
            template_name='myrestaurants/dish_detail.html'),
        name='dish_detail'),

    # Create a restaurant, /myrestaurants/restaurants/create/
    url(r'^restaurants/create/$',
        RestaurantCreate.as_view(),
        name='restaurant_create'),

    # Edit restaurant details, ex.: /myrestaurants/restaurants/1/edit/
    url(r'^restaurants/(?P<pk>\d+)/edit/$',
        UpdateView.as_view(
            model=Restaurant,
            template_name='myrestaurants/form.html',
            form_class=RestaurantForm),
        name='restaurant_edit'),

    # Create a restaurant dish, ex.: /myrestaurants/restaurants/1/dishes/create/
    url(r'^restaurants/(?P<pk>\d+)/dishes/create/$',
        DishCreate.as_view(),
        name='dish_create'),

    # Edit restaurant dish details, ex.: /myrestaurants/restaurants/1/dishes/1/edit/
    url(r'^restaurants/(?P<pkr>\d+)/dishes/(?P<pk>\d+)/edit/$',
        UpdateView.as_view(
            model=Dish,
            template_name='myrestaurants/form.html',
            form_class=DishForm),
        name='dish_edit'),

    # Create a restaurant review, ex.: /myrestaurants/restaurants/1/reviews/create/
    url(r'^restaurants/(?P<pk>\d+)/reviews/create/$',
        review,
        name='review_create'),
]

myrecommendations/myrestaurants/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from datetime import date
# Create your models here.

class Restaurant(models.Model):
    name = models.TextField()
    street = models.TextField(blank=True, null=True)
    number = models.IntegerField(blank=True, null=True)
    city = models.TextField(default="")
    zipCode = models.TextField(blank=True, null=True)
    stateOrProvince = models.TextField(blank=True, null=True)
    country = models.TextField(blank=True, null=True)
    telephone = models. TextField(blank=True, null=True)
    url = models.URLField(blank=True, null=True)
    user = models.ForeignKey(User, default=1)
    date = models.DateField(default=date.today)

    def __str__(self):
        return self.name

class Dish(models.Model):
    name = models.TextField()
    description = models.TextField(blank=True, null=True)
    price = models.DecimalField('Dollar amount', max_digits=8, decimal_places=2, blank=True, null=True)
    user = models.ForeignKey(User, default=1)
    date = models.DateField(default=date.today)
    image = models.ImageField(upload_to='myrestaurants', blank=True, null=True)
    restaurant = models.ForeignKey(Restaurant, null=True, related_name='dishes')
    image = models.ImageField(upload_to="myrestaurants", blank=True, null=True)

    def __str__(self):
        return self.name

class Review(models.Model):
    RATING_CHOICES = ((1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five'))
    rating = models.PositiveSmallIntegerField('Rating (stars)', blank=False, default=3, choices=RATING_CHOICES)
    comment = models.TextField(blank=True, null=True)
    user = models.ForeignKey(User, default=1)
    date = models.DateField(default=date.today)

    class Meta:
        abstract = True

class RestaurantReview(Review):
    restaurant = models.ForeignKey(Restaurant)

myrecommendations/myrestaurants/forms.py
from django.forms import ModelForm
from . models import Restaurant, Dish

class RestaurantForm(ModelForm):
    class Meta:
        model = Restaurant
        exclude = ('user', 'date',)

class DishForm(ModelForm):
    class Meta:
        model = Dish
        exclude = ('user', 'date', 'restaurant',)

myrecommendations/myrestaurants/views.py
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView, CreateView
from . models import RestaurantReview, Restaurant, Dish
from . forms import RestaurantForm, DishForm

# Create your views here.

class RestaurantDetail(DetailView):
    model = Restaurant
    template_name = 'myrestaurants/restaurant_detail.html'

    def get_context_data(self, **kwargs):
        context = super(RestaurantDetail, self).get_context_data(**kwargs)
        context['RATING_CHOICES'] = RestaurantReview.RATING_CHOICES
        return context

class RestaurantCreate(CreateView):
    model = Restaurant
    template_name = 'myrestaurants/form.html'
    form_class = RestaurantForm

    # This method is called when valid form data has been POSTed.
    # It should return an HttpResponse.
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(RestaurantCreate, self).form_valid(form)

class DishCreate(CreateView):
    model = Dish
    template_name = 'myrestaurants/form.html'
    form_class = DishForm

    # This method is called when valid form data has been POSTed.
    # It should return an HttpResponse.
    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.restaurant = Restaurant.objects.get(id=self.kwargs['pk'])
        return super(DishCreate, self).form_valid(form)

def review(request, pk):
    restaurant = get_object_or_404(Restaurant, pk=pk)
    review = RestaurantReview(
        rating=request.POST['rating'],
        comment=request.POST['comment'],
        user=request.user,
        restaurant=restaurant
    )
    review.save()
    return HttpResponseRedirect(reverse('myrestaurants:restaurants_detail', args=(restaurant.id,)))

myrecommendations/templates/myrestaurants/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang='en'>
<head>
    <link rel='stylesheet' href='{% static "myrestaurants/styles/base.css" %}'/>
    <title>{% block title %}MyRestaurants by MyRecommendations.org {% endblock %}</title>
</head>

<body>
    <div id='header'>

        {% block header %}
            {% if user.username %}<p>User {{ user.username }}</p>    
            {% else %}<p><a href="/login/">Signin</a></p>                
            {% endif %}                
        {% endblock %}   

    </div>

    <div id='sidebar'>
        {% block sidebar %}<ul><li><a href="/myrestaurants">Home</a></li></ul>{% endblock sidebar %}
    </div>

    <div id='content'>
        
        {% block content %}
            
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
                    
        {% endblock content %}
            
    </div>

    <div id='footer'>
        {% block footer %}{% endblock footer %}
    </div>
</body>
 </html>

myrecommendations/templates/myrestaurants/dish_detail.html
{% extends 'myrestaurants/base.html' %}


{% block content %}
    <h1>
        {{ dish.name }}
        
        {% if user == dish.user %}
            (<a href ="{% url 'myrestaurants:dish_edit' dish.restaurant.id dish.id %}">edit</a>)
        {% endif %}
    </h1>

    <p>{{ dish.description }} </p>

    
    {% if dish.image %}
        <p><img src="{{ dish.image.url }}" /> </p>
    {% endif %}

    <p>
        Served by
        <a href="{% url 'myrestaurants:restaurant_detail' dish.restaurant.id %}">
            {{ dish.restaurant.name }}
        </a>
    </p>
        
{% endblock content %}


{% block footer %}
    Created by {{ dish.user }} on {{ dish.date }}
{% endblock footer %}
    
    

myrecommendations/templates/myrestaurants/form.html
{% extends 'myrestaurants/base.html' %}


{% block content %}
    <form method='post' enctype='multipart/form-data' action=''>
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type='submit' value='Submit' />
    </form>
{% endblock content %}
    

myrecommendations/templates/myrestaurants/restaurant_detail.html
{% extends 'myrestaurants/base.html' %}


{% block content %}
    
    <h1>
        {{ restaurant.name }}
        
        {% if user == restaurant.user %}
            (<a href="{% url 'myrestaurants:dish_create' restaurant.id %}">edit</a>)
        {% endif %}
    </h1>

    <h2>Address:</h2>

    <p>
        {{ restaurant.street }}, {{ restaurant.number }} <br/>
        {{ restaurant.zipcode }}, {{ restaurant.city }} <br/>
        {{ restaurant.stateOrProvince }} ({{ restaurant.country }})
    </p>

    <h2>
        Dishes
        
        {% if user %}
            (<a href="{%uel 'myrestaurants:dish_create' restaurant.id %}">add</a>)
        {% endif %}
            
    </h2>

    <ul>
        {% for dish in restaurant.dishes.all %}
            <li><a href="{% url 'myrestaurants:dish_detail' restaurant.id dish.id %}"> {{ dish.name }} </a></li>
        {% empty %}<li>Sorry, no dishes for this restaurant yet.</li>
        {% endfor %}
    </ul>

    <h2>Reviews</h2>

    <ul>
        {% for review in restaurant.restaurantreview_set.all %}
        <li>
            <p>{{ review.rating }} star{{ review.rating|pluralize }}</p>
            <p>{{ review.comment }}</p>
            <p>Created by {{ review.user }} on {{ review.date }} </p>
        </li>
        {% endfor %}
    </ul>

    <h3>Add Review</h3>

    <form action="{% url 'myrestaurants:review_create' restaurant.id %}" method="post">
        {% csrf token %}

        Message: <textarea name='comment' id='comment' rows='4'></textarea>
        <p>Rating:</p>
        <p>
            
            {% for rate in RATING_CHOICES %}
                <input type='radio' name='rating' id='rating{{ forloop.counter }}' value='{{ rate.0 }}'/>
                <label for='choice{{ forloop.counter }}'>{{ rate.1 }} star {{rate.0|pluralize}}</label>
                <br/>                
            {% endfor %}
                
        </p>
        <input type='submit' value='Review' />
    </form>

{% endblock content %}


{% block footer %}
    Created by {{ restaurant.user }} on {{ restaurant.date}}
{% endblock footer %}
    
    

myrecommendations/templates/myrestaurants/restaurant_list.html
{% extends 'myrestaurants/base.html' %}


{% block content %}
    <h1>
        Restaurants
        {% if user %}(<a href='{% url 'myrestaurants:restaurant_create' %}'>add</a>){% endif %}
    </h1>

    <ul>
        
        {% for restaurant in latest_restaurant_list  %}
            <li><a href="{% url 'myrestaurants:restaurant_detail' restaurant.id %}"> {{ restaurant.name }}</a></li>
            {% empty %}<li>Sorry, no restaurants registered yet.</li>
        {% endfor %}
    </ul>
{% endblock content %}
    